# Generated by Django 6.1.1 on 2026-09-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('resumen', models.CharField(blank=True, max_length=300)),
                ('contenido', models.TextField()),
                ('autor', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], default='borrador', max_length=10)),
                ('icono', models.CharField(blank=True, default='📝', max_length=10)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
