# Generated by Django 6.1.1 on 2026-09-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='numero_tarjeta',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='vencimiento_tarjeta',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='contraparte',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('deposito', 'Depósito'), ('extraccion', 'Extracción'), ('transferencia_enviada', 'Transferencia enviada'), ('transferencia_recibida', 'Transferencia recibida')], max_length=24),
        ),
    ]
