# Generated by Django 6.1.1 on 2026-09-22 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0002_cuenta_numero_tarjeta_cuenta_vencimiento_tarjeta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='alias',
            field=models.CharField(blank=True, max_length=40, unique=True, validators=[django.core.validators.RegexValidator(message='El alias va en minusculas y con el formato palabra.palabra.palabra.', regex='^[a-z0-9]+(\\.[a-z0-9]+){2}$')]),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cbu',
            field=models.CharField(blank=True, max_length=22, unique=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
