# Generated by Django 6.1.1 on 2026-09-22 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0003_cuenta_alias_cuenta_cbu_cuenta_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='tarjeta_bloqueada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='ultimo_rendimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='contraparte',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('deposito', 'Depósito'), ('extraccion', 'Extracción'), ('transferencia_enviada', 'Transferencia enviada'), ('transferencia_recibida', 'Transferencia recibida'), ('pago_servicio', 'Pago de servicio'), ('recarga_celular', 'Recarga de celular'), ('rendimiento', 'Rendimiento')], max_length=24),
        ),
        migrations.CreateModel(
            name='SolicitudDinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(blank=True, max_length=140)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=10)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('resuelta', models.DateTimeField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to='banca.cuenta')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_hechas', to='banca.cuenta')),
            ],
            options={
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apodo', models.CharField(blank=True, max_length=40)),
                ('agregado', models.DateTimeField(auto_now_add=True)),
                ('cuenta_guardada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardado_por', to='banca.cuenta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['apodo', 'id'],
                'unique_together': {('usuario', 'cuenta_guardada')},
            },
        ),
    ]
