# Generated by Django 6.1.1 on 2026-10-01 00:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banca', '0004_cuenta_tarjeta_bloqueada_cuenta_ultimo_rendimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='es_comercio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='nombre_comercio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='saldo_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('deposito', 'Depósito'), ('extraccion', 'Extracción'), ('transferencia_enviada', 'Transferencia enviada'), ('transferencia_recibida', 'Transferencia recibida'), ('pago_servicio', 'Pago de servicio'), ('recarga_celular', 'Recarga de celular'), ('rendimiento', 'Rendimiento'), ('compra_usd', 'Compra de dólares'), ('venta_usd', 'Venta de dólares'), ('prestamo_acreditado', 'Préstamo acreditado'), ('pago_cuota_prestamo', 'Pago de cuota de préstamo'), ('plazo_fijo_creado', 'Plazo fijo'), ('plazo_fijo_rescatado', 'Rescate de plazo fijo'), ('seguro_contratado', 'Seguro contratado')], max_length=24),
        ),
        migrations.CreateModel(
            name='PlazoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasa_anual', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dias', models.PositiveSmallIntegerField()),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('rescatado', 'Rescatado')], default='activo', max_length=10)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plazos_fijos', to='banca.cuenta')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasa_interes', models.DecimalField(decimal_places=2, default=Decimal('0.15'), max_digits=4)),
                ('cantidad_cuotas', models.PositiveSmallIntegerField()),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuotas_pagadas', models.PositiveSmallIntegerField(default=0)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pagado', 'Pagado')], default='activo', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='banca.cuenta')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('costo_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_contratacion', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguros', to='banca.cuenta')),
            ],
            options={
                'ordering': ['-fecha_contratacion'],
            },
        ),
    ]
